// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfptuWHhTyXxmV7G4bxvVjoAPbAeNdwCc',
    appId: '1:379964520338:web:8d1fa8e6b0f5f36f2a334b',
    messagingSenderId: '379964520338',
    projectId: 'sasper-6fc6c',
    authDomain: 'sasper-6fc6c.firebaseapp.com',
    storageBucket: 'sasper-6fc6c.firebasestorage.app',
    measurementId: 'G-F3GCKC1RNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-DFxSeEttgWjc7Rlu192ldkWX_esXjo',
    appId: '1:379964520338:android:758b6ab9f4d390362a334b',
    messagingSenderId: '379964520338',
    projectId: 'sasper-6fc6c',
    storageBucket: 'sasper-6fc6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3b5nybrcTrrm1_oADMJMxxpMLL2pU1uQ',
    appId: '1:379964520338:ios:cc0e515676686bb02a334b',
    messagingSenderId: '379964520338',
    projectId: 'sasper-6fc6c',
    storageBucket: 'sasper-6fc6c.firebasestorage.app',
    iosBundleId: 'com.example.sasper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3b5nybrcTrrm1_oADMJMxxpMLL2pU1uQ',
    appId: '1:379964520338:ios:935106218f0fa04f2a334b',
    messagingSenderId: '379964520338',
    projectId: 'sasper-6fc6c',
    storageBucket: 'sasper-6fc6c.firebasestorage.app',
    iosBundleId: 'com.example.finanzasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfptuWHhTyXxmV7G4bxvVjoAPbAeNdwCc',
    appId: '1:379964520338:web:ae0f111ff9530fec2a334b',
    messagingSenderId: '379964520338',
    projectId: 'sasper-6fc6c',
    authDomain: 'sasper-6fc6c.firebaseapp.com',
    storageBucket: 'sasper-6fc6c.firebasestorage.app',
    measurementId: 'G-QK0MTNCZ30',
  );

}